### ISSUE TITLE
Sample lengths in an unlabeled c3D file

### ISSUE THREAD

**Issue by marnunez** [aclouthier/auto-marker-label#3]
Hi! I've successfully trained the network with some labeled c3ds using the default options of 10 epochs and 120 window size. However, when I offer an unlabeld c3d track, I get the following error:

```
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\dash\dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\dash\dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "markerLabelGUI.py", line 538, in label_data
    pts, modelpath, trainvalpath, markersetpath, fs, windowSize
  File "D:\Documents\auto-marker-label\automarkerlabel.py", line 1251, in marker_label
    probWindow = predict_nn(modelpath, pts, windowIdx, scaleVals, num_mks, max_len)
  File "D:\Documents\auto-marker-label\automarkerlabel.py", line 1157, in predict_nn
    outputs = net(data, data_lens)
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Documents\auto-marker-label\automarkerlabel.py", line 1015, in forward
    x.float(), x_lens, batch_first=True, enforce_sorted=False
  File "C:\tools\miniconda3\envs\AutoLabel\lib\site-packages\torch\nn\utils\rnn.py", line 233, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0
```

From what I read, this happens when empty data is fed to either the training algorithm or the labeling process, but I have no empty markers. I am using gait c3d files, where missing markers are much more common, specially at the beginning and the end. I attach an unlabeled sample here, any advice would be really appreciated.
[unlabeled_sample.zip](https://github.com/aclouthier/auto-marker-label/files/5928405/unlabeled_sample.zip)

**Comment by aclouthier** [comment]
It was because there are 4 frames at the beginning when only one marker is visible. I just added a check for that so I think it should work now. Let me know if that solves the problem.

**Comment by marnunez** [comment]
Amazing, that did it, thanks!

![image](https://user-images.githubusercontent.com/1470552/107060205-72efed00-67b5-11eb-813b-aee790b2cfec.png)

I'll play around with some of the parameters now, I trained the model with just 7 trials from the same subject, and left one for testing. With the current settings and that scarce training, it misses most of the markers, and more worryingly, some wrong labels have really high confidence. I'll play around with window size (we capture at 100 Hz, so that might be a factor) and epochs, and see what I can get.

Really looking forward to your paper!

**Comment by aclouthier** [comment]
Glad it's running at least! 
Another thing to check is the rotation of the person. The data are all rotated so that the person faces +x for training, so you need to do the same when labelling (or should be anyway, using the two markers you specify). I noticed in your file the person walks forward in y which would need a -90 in the 'Rotation about z' box in the GUI. I can't see the axis labels in your picture, so not sure if you've taken care of that already.

You can also always try generating the simulated trajectories for training to give it some more data to train on.

**Comment by marnunez** [comment]
This works amazingly!

I changed all my c3Ds in training to face +X, and trained 300 epochs (by the way, instead of fixing epochs, could this be done until a threshold loss is achieved?). Then, as you suggested, faced my test trials +x in the markerLabelGUI.

![image](https://user-images.githubusercontent.com/1470552/107076847-c9b3f180-67ca-11eb-9ca3-f1c15d451c68.png)

**Comment by aclouthier** [comment]
Great!
Yes, that is a good suggestion, I should look into having a criterion for stopping the training.
